### ISSUE TITLE
Copied Learn project folder is null

### ISSUE THREAD

**Issue by Dibro89** [karashevich/training#30]
Just installed fresh Intellij IDEA 2017.3 and selected training plugin in first startup wizard.
Clicking on "Learn Itellij IDEA" does nothing.

log: `java.lang.Exception: Copied Learn project folder is null`

Manually created `IdeaProjects` in default location.
Clicked again and `LearnProject` folder appeared inside `IdeaProjects`, same exception in log thought.

After a few minutes clicked the button again and everything is working now.

**Comment by Dibro89** [comment]
Manually created `IdeaProjects` in default location.
Clicked again and `LearnProject` folder appeared inside `IdeaProjects`, same exception in log thought.
After a few minutes clicked the button again and everything is working now.

**Comment by karashevich** [comment]
@Dibro89 thanks for logging the issue. Could you paste here a stack trace from this error ([how to find a log](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files)). And could you also write what OS do you use?

**Comment by karashevich** [comment]
Thanks, @Dibro89. Finally found a bug and fixed in 0.8.59
